name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create .env file for static build
        run: |
          cat <<EOF > .env
          NEXT_PUBLIC_OPENAI_API_KEY=${{ secrets.NEXT_PUBLIC_OPENAI_API_KEY }}
          NEXT_PUBLIC_OPENAI_REALTIME_URL=${{ secrets.NEXT_PUBLIC_OPENAI_REALTIME_URL }}
          NEXT_PUBLIC_SESSION_URL=${{ secrets.NEXT_PUBLIC_SESSION_URL }}
          NEXT_PUBLIC_OPENAI_TRANSCRIPTION_REALTIME_URL=${{ secrets.NEXT_PUBLIC_OPENAI_TRANSCRIPTION_REALTIME_URL }}
          EOF

      - name: Install dependencies
        run: npm ci

      - name: Build static site
        run: npm run build:static

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
